# Generated by Django 4.1.3 on 2022-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud02', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.CharField(max_length=20)),
                ('emp_role', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField()),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
